version: '3.4'

networks:
  cm-net:
    driver: bridge

volumes:
  rabbit_data: {}
  mssql_data: {}

services:

  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/lib/mssql/data